### PR TITLE
fix: validator worker startup

### LINKED ISSUE #146: Refactor: Implement validator worker startup process

### PR DESCRIPTION
**Pull request by samparsky**
Fixes #146

### CODE REVIEW

File: validator_worker/src/main.rs [hunk 1]
```diff
@@ -98,26 +120,100 @@ fn main() {
...
+
+async fn infinite<A: Adapter + 'static>(args: Args<A>) -> Result<(), ()> {
+    loop {
+        let arg = args.clone();
+        let delay_future =
+            Delay::new(Instant::now().add(Duration::from_secs(arg.config.wait_time as u64)));
+        let joined = join(iterate_channels(arg), delay_future.compat());
+        match joined.await {
+            (_, Err(e)) => eprintln!("{}", e),
+            _ => println!("finished processing channels"),
```
Comment (elpiel) [inline validator_worker/src/main.rs]: Is this going to show up every `arg.config.wait_time` seconds? Is this necessary for the output?

File: validator_worker/src/main.rs [hunk 2]
```diff
@@ -98,26 +120,100 @@ fn main() {
...
+        };
+    }
+}
+
+async fn iterate_channels<A: Adapter + 'static>(args: Args<A>) -> Result<(), ()> {
+    let channels = all_channels(&args.sentry_url, args.whoami.clone())
+        .await
+        .expect("Failed to get channels");
```
Comment (elpiel) [inline validator_worker/src/main.rs]: shouldn't we then just return from the function? I think if Sentry is down for a bit, then the validator will exit this way, which is not idea IMO.

File: validator_worker/src/main.rs [hunk 3]
```diff
@@ -98,26 +120,100 @@ fn main() {
...
+    let channels_size = channels.len();
+
+    try_join_all(
+        channels.into_iter().map(|channel| {
+            validator_tick(args.adapter.clone(), channel, &args.config, &args.whoami)
+        }),
+    )
+    .await
+    .expect("Failed to iterate channels");
```
Comment (elpiel) [inline validator_worker/src/main.rs]: You won't need this if the `validator_tick` is not returning anything ( see comment bellow).

File: validator_worker/src/main.rs [hunk 4]
```diff
@@ -98,26 +120,100 @@ fn main() {
...
+
+    Ok(())
+}
+
+async fn validator_tick<A: Adapter + 'static>(
+    adapter: Arc<Mutex<A>>,
+    channel: Channel,
+    config: &Config,
+    whoami: &str,
+) -> Result<(), ()> {
```
Comment (elpiel) [inline validator_worker/src/main.rs]: I think you can just remove the return type and not use a Result.

File: validator_worker/src/sentry_interface.rs [hunk 5]
```diff
@@ -114,13 +108,24 @@ impl<T: Adapter + 'static> SentryApi<T> {
             .and_then(|mut res: Response| res.json::<ValidatorMessageResponse>())
             .compat();
 
-        future.await
+        match future.await {
```
Comment (elpiel) [inline validator_worker/src/sentry_interface.rs]: Side note: We can simplify this.

File: validator_worker/src/sentry_interface.rs [hunk 6]
```diff
@@ -225,23 +227,19 @@ fn handle_http_error(e: reqwest::Error, url: &str) {
...
     if first_page.total_pages < 2 {
         Ok(first_page.channels)
     } else {
         let mut all: Vec<ChannelAllResponse> = try_join_all(
-            (0..first_page.total_pages).map(|i| fetch_page(url.clone(), i, validator.clone())),
+            (0..first_page.total_pages).map(|i| fetch_page(url.clone(), i, whoami.clone())),
         )
         .await
-        .unwrap();
+        .expect("Failed to fetch all channels");
```
Comment (elpiel) [inline validator_worker/src/sentry_interface.rs]: Shouldn't this be returned as an error, instead of crashing the validator? Again - Sentry down for a bit, network issues and etc., will cause it to blow up and stop the validator.

File: primitives/src/sentry.rs [hunk 7]
```diff
@@ -80,10 +80,16 @@ pub struct SuccessResponse {
...
+pub struct ValidatorMessage {
     pub from: String,
     pub received: DateTime<Utc>,
-    pub msg: Vec<MessageTypes>,
+    pub msg: MessageTypes,
+}
+
+#[derive(Serialize, Deserialize, Debug)]
+#[serde(rename_all = "camelCase")]
+pub enum ValidatorMessageResponse {
```
Comment (elpiel) [inline primitives/src/sentry.rs]: I think this should be in sentry_interface and not public as it's only used for deserializing in `sentry_interface`

Comment (samparsky) [reply primitives/src/sentry.rs]: it's needed it in sentry too for `ValidatorMessageResponse`

File: validator_worker/src/main.rs (hunk 4 above)
Comment (samparsky) [reply validator_worker/src/main.rs]: That's added because of `try_join_all`

File: validator_worker/src/sentry_interface.rs (hunk 5 above)
Comment (samparsky) [reply validator_worker/src/sentry_interface.rs]: yeah true

File: validator_worker/src/sentry_interface.rs (hunk 6 above)
Comment (samparsky) [reply validator_worker/src/sentry_interface.rs]: This could be helpful in cases of wrong sentry url

File: validator_worker/src/main.rs (hunk 1 above)
Comment (samparsky) [reply validator_worker/src/main.rs]: It's meant to be a performance metric helper. The println! will be changed to logger when we have the implementation.

File: validator_worker/src/main.rs (hunk 2 above)
Comment (samparsky) [reply validator_worker/src/main.rs]: yeah true

File: validator_worker/src/main.rs (hunk 1 above)
Comment (samparsky) [reply validator_worker/src/main.rs]: Also, clippy shows warnings if the error variant isn't handled

File: validator_worker/src/main.rs (hunk 3 above)
Comment (samparsky) [reply validator_worker/src/main.rs]: If you don't handle Err variant for Result<>, clippy would show warnings

File: primitives/src/sentry.rs [hunk 8]
```diff
@@ -80,10 +80,16 @@ pub struct SuccessResponse {
...
+    ValidatorMessages(Option<Vec<ValidatorMessage>>),
```
Comment (Ivshti) [inline primitives/src/sentry.rs]: do we need an `Option` here; what extra meaning does it add on top of just sending back an empty vector?

File: validator_worker/src/follower.rs [hunk 9]
```diff
@@ -24,24 +24,20 @@ enum NewStateResult {
...
-            MessageTypes::NewState(new_state) => Some(new_state.clone()),
-            _ => None,
-        });
+    let new_msg = match new_msg_response {
+        Some(MessageTypes::NewState(new_state)) => Some(new_state),
+        _ => None,
+    };
+
     let our_latest_msg_response = iface
         .get_our_latest_msg("ApproveState+RejectState".to_string())
```
Comment (Ivshti) [inline validator_worker/src/follower.rs]: perhaps this api would be nicer if it gets `&[&str]` so that we avoid the `+` hack

File: validator_worker/src/lib.rs [hunk 10]
```diff
@@ -61,12 +61,14 @@ mod test {
         };
         let config = configuration("development", None).expect("Dev config should be available");
         let dummy_adapter = DummyAdapter::init(adapter_options, &config).expect("init adadpter");
+        let whoami = dummy_adapter.whoami();
 
-        SentryApi::new(
-            Arc::new(RwLock::new(dummy_adapter)),
+        SentryApi::init(
+            Arc::new(Mutex::new(dummy_adapter)),
```
Comment (Ivshti) [inline validator_worker/src/lib.rs]: is there a reason for using a `Mutex` rather than a `Rwlock`

File: validator_worker/src/main.rs (hunk 1 above)
Comment (elpiel) [reply validator_worker/src/main.rs]: You can still do a `_ => {}`, but that's ok for now. If it's annoying posting `finished processing channels` every `wait_time` seconds we can remove it.

File: validator_worker/src/sentry_interface.rs [hunk 11]
```diff
@@ -227,21 +240,19 @@ fn handle_http_error(e: reqwest::Error, url: &str) {
...
-        .await
-        .expect("Failed to get channels from sentry url");
+    let first_page = fetch_page(url.clone(), 0, whoami.clone()).await?;
+
     if first_page.total_pages < 2 {
         Ok(first_page.channels)
     } else {
         let mut all: Vec<ChannelAllResponse> = try_join_all(
-            (0..first_page.total_pages).map(|i| fetch_page(url.clone(), i, validator.clone())),
+            (0..first_page.total_pages).map(|i| fetch_page(url.clone(), i, whoami.clone())),
```
Comment (elpiel) [inline validator_worker/src/sentry_interface.rs]: Why are we fetching the first page again btw?
