### PR TITLE
Testing setup improvements & fix for ganache second instance snapshot

### LINKED ISSUE #403: [CI] Use a snapshot for Ethereum adapter testing
Related to #380 & PR #385 and comment https://github.com/AdExNetwork/adex-validator-stack-rust/pull/385#discussion_r629963448

### PR DESCRIPTION
**Pull request by elpiel**
Closes #403
Only a single test function deploys contracts to test if a newly deployed token deposits work.

### CODE REVIEW

File: test_harness/src/lib.rs [hunk 1]
```diff
@@ -765,14 +995,45 @@ mod tests {
...
+            // Channel 2
+            let _channel_2_heartbeat = leader_sentry
+                .get_our_latest_msg(CAMPAIGN_2.channel.id(), &["Heartbeat"])
+                .await
+                .expect("Should fetch Heartbeat from Leader")
+                .map(|message| Heartbeat::try_from(message).expect("Should be Heartbeat"))
+                .expect("Should have a Heartbeat in Leader for the Campaign 2 channel");
+
+            // Channel 3
+            let _channel_2_heartbeat = leader_sentry
```
Comment (simzzz) [inline test_harness/src/lib.rs]:
```suggestion
            let _channel_3_heartbeat = leader_sentry
```

The unused variable is not named correctly.

**Review by simzzz — CHANGES_REQUESTED** [review]

**Review by simzzz — APPROVED** [review]
