### PR TITLE
Issue #278 Propagation logging

### LINKED ISSUE #278: SentryApi propagation logging and `try_join_all` fix
- [x] Move logging out of `SentryApi.propagate()` #281 
- [x] Fix `try_join_all` #281 

1. We can return a more complete error that can indicate exactly which validator request (Channel id, Validator Id, etc) failed and why (providing the `reqwest::Error`)
2. `try_join_all` will fail on the first error, which means that if the Follower errors for a reason, the Leader might not get the `message` as `try_join_all` can return the error and cancel the other futures (see https://docs.rs/futures/0.3.4/futures/future/fn.try_join_all.html)

https://github.com/AdExNetwork/adex-validator-stack-rust/blob/e8dd5c07ec/validator_worker/src/sentry_interface.rs#L81

### PR DESCRIPTION
**Pull request by elpiel**
Fixes #278 #280

### CODE REVIEW

File: sentry/src/middleware/auth.rs [hunk 1]
```diff
@@ -83,7 +83,7 @@ fn get_request_ip(req: &Request<Body>) -> Option<String> {
         .get("true-client-ip")
         .or_else(|| req.headers().get("x-forwarded-for"))
         .and_then(|hv| hv.to_str().map(ToString::to_string).ok())
-        .map(|token| token.split(',').nth(0).map(ToString::to_string))
+        .map(|token| token.split(',').next().map(ToString::to_string))
```
[the remark this answers is not in the document]
Comment (elpiel) [reply sentry/src/middleware/auth.rs]: `Clippy` - apparently it's an error in the new clippy

File: validator_worker/src/main.rs [hunk 2]
```diff
@@ -195,15 +196,16 @@ async fn validator_tick<A: Adapter + 'static>(
     channel: Channel,
     config: &Config,
     logger: &Logger,
-) -> Result<(), ValidatorWorkerError<A::AdapterError>> {
+) -> Result<(ChannelId, Box<dyn Debug>), ValidatorWorkerError<A::AdapterError>> {
```
Comment (samparsky) [inline validator_worker/src/main.rs]: why is it validator_tick returning `(ChannelId, Box<dyn Debug>)` if we don't need / use it?

Comment (elpiel) [reply validator_worker/src/main.rs]: It's logged
