### PR TITLE
Remaining spender all tests

### LINKED ISSUE #392: AIP #61 v5: GET /channel/:id/spender/all
## https://github.com/AdExNetwork/aips/issues/61

Related to #391 as this should return all spenders limits 

- [x] Route impl #424 
- [x] Pagination of response #441

### LINKED ISSUE #450: Ordering issue in test gets_all_spendables_for_channel
There is an ordering issue with this tests.
@simzzz please check it out.

The build that shows the error bellow can be found here: https://github.com/AmbireTech/adex-validator-stack-rust/runs/4023055318?check_suite_focus=true

> ---- db::spendable::test::gets_all_spendables_for_channel stdout ----
thread 'db::spendable::test::gets_all_spendables_for_channel' panicked at 'assertion failed: `(left == right)`
  left: `[Spendable { spender: Address(0xb7d3f81e857692d13e9d63b232a90f4a1793189e), channel: Channel { leader: ValidatorId(0xce07cbb7e054514d590a0262c93070d838bfba2e), follower: ValidatorId(0xc91763d7f14ac5c5ddfbcd012e0d2a61ab9bded3), guardian: Address(0x2892f6c41e0718eeedd49d98d648c789668ca67d), token: Address(0x73967c6a0904aa032c103b4104747e88c566b1a2), nonce: Nonce(987654321) }, deposit: Deposit { total: UnifiedNum(1.00000000), still_on_create2: UnifiedNum(0.00500000) } }, Spendable { spender: Address(0x20754168c00a6e58116ccfd0a5f7d1bb66c5de9d), channel: Channel { leader: ValidatorId(0xce07cbb7e054514d590a0262c93070d838bfba2e), follower: ValidatorId(0xc91763d7f14ac5c5ddfbcd012e0d2a61ab9bded3), guardian: Address(0x2892f6c41e0718eeedd49d98d648c789668ca67d), token: Address(0x73967c6a0904aa032c103b4104747e88c566b1a2), nonce: Nonce(987654321) }, deposit: Deposit { total: UnifiedNum(1.00000000), still_on_create2: UnifiedNum(0.00500000) } }]`,
 right: `[Spendable { spender: Address(0x20754168c00a6e58116ccfd0a5f7d1bb66c5de9d), channel: Channel { leader: ValidatorId(0xce07cbb7e054514d590a0262c93070d838bfba2e), follower: ValidatorId(0xc91763d7f14ac5c5ddfbcd012e0d2a61ab9bded3), guardian: Address(0x2892f6c41e0718eeedd49d98d648c789668ca67d), token: Address(0x73967c6a0904aa032c103b4104747e88c566b1a2), nonce: Nonce(987654321) }, deposit: Deposit { total: UnifiedNum(1.00000000), still_on_create2: UnifiedNum(0.00500000) } }, Spendable { spender: Address(0xb7d3f81e857692d13e9d63b232a90f4a1793189e), channel: Channel { leader: ValidatorId(0xce07cbb7e054514d590a0262c93070d838bfba2e), follower: ValidatorId(0xc91763d7f14ac5c5ddfbcd012e0d2a61ab9bded3), guardian: Address(0x2892f6c41e0718eeedd49d98d648c789668ca67d), token: Address(0x73967c6a0904aa032c103b4104747e88c566b1a2), nonce: Nonce(987654321) }, deposit: Deposit { total: UnifiedNum(1.00000000), still_on_create2: UnifiedNum(0.00500000) } }]`', sentry/src/db/spendable.rs:275:9
stack backtrace:

### PR DESCRIPTION
**Pull request by simzzz**

### CODE REVIEW

File: validator_worker/src/sentry_interface.rs [hunk 1]
```diff
@@ -161,26 +161,51 @@ impl<A: Adapter + 'static> SentryApi<A> {
...
     }
 
-    // TODO: Pagination & use of `AllSpendersResponse`
-    pub async fn get_all_spenders(
+    pub async fn get_spenders_page(
         &self,
-        channel: ChannelId,
-    ) -> Result<HashMap<Address, Spender>, Error> {
+        channel: &ChannelId,
+        page: u64,
```
Comment (elpiel) [inline validator_worker/src/sentry_interface.rs:168]: Could you please add a documentation comment which mentions that the `page` always starts from `0`

File: validator_worker/src/sentry_interface.rs [hunk 2]
```diff
@@ -161,26 +161,51 @@ impl<A: Adapter + 'static> SentryApi<A> {
...
+    ) -> Result<AllSpendersResponse, Error> {
         let url = self
             .whoami
             .url
-            .join(&format!("v5/channel/{}/spender/all", channel))
+            .join(&format!("v5/channel/{}/spender/all?page={}", channel, page))
             .expect("Should not error when creating endpoint");
 
-        self.client
+        let first_page: AllSpendersResponse = self
```
Comment (elpiel) [inline validator_worker/src/sentry_interface.rs]: It's not the first page, is it? it's the `page` page.

Also, you don't need a separate variable for this. You can leave the code as it was before (without a variable nor Ok(first_page))

File: validator_worker/src/sentry_interface.rs [hunk 3]
```diff
@@ -378,3 +403,151 @@ pub mod campaigns {
...
+        UnifiedNum,
+    };
+    use std::str::FromStr;
+    use wiremock::{
+        matchers::{method, path, query_param},
+        Mock, MockServer, ResponseTemplate,
+    };
+
+    #[tokio::test]
+    async fn test_get_all_spenders() {
```
Comment (elpiel) [inline validator_worker/src/sentry_interface.rs:428]: Create a Hashmap with all spenders and for each page response create a simple `vec![].collect()` so that you can `assert_eq!` more easily without repetition

File: validator_worker/src/sentry_interface.rs [hunk 4]
```diff
@@ -378,3 +403,151 @@ pub mod campaigns {
...
+
+        assert!(expected_response.keys().len() == res.keys().len());
+        // Is page 1 included
+        assert!(res.contains_key(&ADDRESSES["user"]) && res.contains_key(&ADDRESSES["publisher"]));
+        // Is page 2 included
+        assert!(
+            res.contains_key(&ADDRESSES["publisher2"]) && res.contains_key(&ADDRESSES["creator"])
+        );
+        // Is page 3 included
+        assert!(res.contains_key(&ADDRESSES["tester"]));
```
Comment (elpiel) [inline validator_worker/src/sentry_interface.rs]: Assertions must be more that `assert!` contains key. If logic doesn't work => no additional info will be available on what has happened.

use something like `assert_eq!(page_one_expected, page_one_actual)`

**Review by elpiel — APPROVED** [review]
